package com.gitc.home.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContact<M extends BaseContact<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	public java.lang.String getPosition() {
		return get("position");
	}

	public void setInterest(java.lang.String interest) {
		set("interest", interest);
	}

	public java.lang.String getInterest() {
		return get("interest");
	}

	public void setInterestOther(java.lang.String interestOther) {
		set("interest_other", interestOther);
	}

	public java.lang.String getInterestOther() {
		return get("interest_other");
	}

	public void setSuggest(java.lang.String suggest) {
		set("suggest", suggest);
	}

	public java.lang.String getSuggest() {
		return get("suggest");
	}

}
