package com.gitc.home.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchedule<M extends BaseSchedule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setReginId(java.lang.Integer reginId) {
		set("regin_id", reginId);
	}

	public java.lang.Integer getReginId() {
		return get("regin_id");
	}

	public void setReginName(java.lang.String reginName) {
		set("regin_name", reginName);
	}

	public java.lang.String getReginName() {
		return get("regin_name");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("date_str", dateStr);
	}

	public java.lang.String getDateStr() {
		return get("date_str");
	}

	public void setTimeStr(java.lang.String timeStr) {
		set("time_str", timeStr);
	}

	public java.lang.String getTimeStr() {
		return get("time_str");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setJob(java.lang.String job) {
		set("job", job);
	}

	public java.lang.String getJob() {
		return get("job");
	}

}
