package com.gitc.home.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setText(java.lang.String text) {
		set("text", text);
	}

	public java.lang.String getText() {
		return get("text");
	}

	public void setConfrenceId(java.lang.Integer confrenceId) {
		set("confrence_id", confrenceId);
	}

	public java.lang.Integer getConfrenceId() {
		return get("confrence_id");
	}

}
