package com.gitc.home.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("confrence", "id", Confrence.class);
		arp.addMapping("gitc", "id", Gitc.class);
		arp.addMapping("guest", "id", Guest.class);
		arp.addMapping("opt", "id", Opt.class);
		arp.addMapping("region", "id", Region.class);
		arp.addMapping("schedule", "id", Schedule.class);
		arp.addMapping("speaker", "id", Speaker.class);
		arp.addMapping("user_sh", "id", UserSh.class);
	}
}

