package com.gitc.home.model;

import com.gitc.home.model.base.BaseConfrence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Confrence extends BaseConfrence<Confrence> {
	public static final Confrence dao = new Confrence();
}
