package com.gitc.home.model;

import com.gitc.home.model.base.BaseContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact();

	public void saveContact(Contact c) {
			c.save();
	}
}
