package com.gitc.home.model;

import com.gitc.home.model.base.BaseContact;
import com.jfinal.plugin.activerecord.Db;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact();

	public void saveContact(Contact c) {
			c.save();
	}

	public List<Contact> getAllContactsFromDb() {
		return dao.find("select * from `contact` where not if_delete order by add_time desc, if_close");
	}

	public void deleteContact(int id) {
		Db.update("update `contact` set if_delete=true where id =" + id);
	}
}
