package com.gitc.home.model;

import com.gitc.home.model.base.BaseGitc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gitc extends BaseGitc<Gitc> {
	public static final Gitc dao = new Gitc();
}
