package com.gitc.home.model;

import java.util.List;

import com.gitc.home.model.base.BaseOpt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Opt extends BaseOpt<Opt> {
	public static final Opt dao = new Opt();
 
	public Opt getSponsor() {
		return dao.findFirst("select * from `opt` where type = 'sponsor'");
	}

	public Opt getMedia() {
		return dao.findFirst("select * from `opt` where type = 'media'");
	}

	public Opt getGuide() {
		return dao.findFirst("select * from `opt` where type = 'guide'");
	}

	public List<Opt> getAllBanners() {
		// TODO Auto-generated method stub
		return dao.find("select * from `opt` where type = 'banner'");
	}
}
