package com.gitc.home.model;

import com.gitc.home.model.base.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region();
	
	public static final String[] regions = new String[]{"","主会场","云专场","运维专场","大数据专场","技术&产品专场"};
}
