package com.gitc.home.model;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.gitc.home.model.base.BaseSchedule;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Schedule extends BaseSchedule<Schedule> {
	public static final Schedule dao = new Schedule();
	
	public List<Schedule> getAllSchedulesFromDb() {
		return dao.find("select * from `schedule` order by id asc");
	}

	public void saveOrUpdate(Schedule schedule) {
		if(schedule.get("id")==null){
			schedule.save();
		}else{
			schedule.update();
		}
	}

	public void importAll(final List<Schedule> schedules) {
		Db.tx(new IAtom() {
			public boolean run() throws SQLException {
				Db.update("delete from `schedule`");
				for(Schedule sp : schedules){
					sp.save();
				}
				return true;
			}
		});
	}

	public List<Object> findSchedulesById(int id) {
		List<Schedule> scs = dao.find("select * from `schedule` where regin_id = ?", id);
		List<Object> result = new ArrayList<Object>();
		String idx_date = "";
		for(Schedule s : scs){
			if(idx_date.equals(s.getDateStr())){
				result.add(s);
			}else{
				idx_date = s.getDateStr();
				result.add(idx_date);
				result.add(s);
			}
		}
		return result;
	}
}
