package com.gitc.home.model;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.gitc.home.model.base.BaseUserSh;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSh extends BaseUserSh<UserSh> {
	public static final UserSh dao = new UserSh();
	
	public List<UserSh> getAllUserShsFromDb() {
		return dao.find("select * from `user_sh` order by username asc");
	}

	public List<UserSh> getAllUserShs() {
		return dao.find("select * from `user_sh` order by username asc");
	}
	
	public List<UserSh> getAllUserShs(int t) {
		return dao.find("select * from `user_sh` where type = ? order by username asc", t);
	}
	
	public void saveOrUpdate(UserSh user_sh) {
		if(user_sh.getId()==null){
			user_sh.save();
		}else{
			user_sh.update();
		}
	}

	public void importAll(final List<UserSh> list) {
		List<UserSh> oldps = getAllUserShs();
		final Map<String,String> pic_map = new HashMap<String, String>();
		for(UserSh p : oldps){
			pic_map.put(p.getUsername(), p.getImage());
		}
		Db.tx(new IAtom() {
			public boolean run() throws SQLException {
				Db.update("delete from `user_sh`");
				for(UserSh g : list){
					g.setImage(pic_map.get(g.getUsername()));
					g.save();
				}
				return true;
			}
		});
	}

	public UserSh getUserShById(int id) {
		return dao.findById(id);
	}

	public void importAll(final List<UserSh> list, final int t) {
		List<UserSh> oldps = getAllUserShs(t);
		final Map<String,String> pic_map = new HashMap<String, String>();
		for(UserSh p : oldps){
			pic_map.put(p.getUsername(), p.getImage());
		}
		Db.tx(new IAtom() {
			public boolean run() throws SQLException {
				Db.update("delete from `user_sh` where type = ?", t);
				for(UserSh g : list){
					g.setImage(pic_map.get(g.getUsername()));
					g.save();
				}
				return true;
			}
		});
	}

	public List<UserSh> getAllUserShs(int t, int page, int count) {
		return dao.find("select * from `user_sh` where type = ? order by username "
				+ "asc limit ?,?", t, (page-1)*count, count);
	}
}
